apiVersion: v1
kind: Secret
metadata:
  name: database-secret
type: Opaque
data:
  dbname: <base64-encoded-value-of-dbname>
  username: <base64-encoded-value-of-username>
  password: <base64-encoded-value-of-password>
  dbport: <base64-encoded-value-of-dbport>
