apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  mongo-user: ZXhhbXBsZV91c2VybmFtZQ==  # base64-encoded value of "example_username"
  mongo-password: cGFzc3dvcmQxMjM=          # base64-encoded value of "password123"
